### ISSUE TITLE
Improve error when actual fee exceeds max fee

### ISSUE THREAD

**Issue by FabijanC** [0xSpaceShard/starknet-devnet#185]
alpha-goerli outputs:
```
Actual fee exceeded max fee.
4952850074293 > 1
```

Devnet outputs:
```
"(500, {'code': <StarknetErrorCode.TRANSACTION_FAILED: 39>, 'message': 'Error message: SafeUint256: subtraction overflow\\nError at pc=0:385:\\nAn ASSERT_EQ instruction failed: 0 != 1.\\nCairo traceback (most recent call last):\\nUnknown location (pc=0:1477)\\nUnknown location (pc=0:1454)\\nUnknown location (pc=0:764)\\nError message: ERC20: transfer amount exceeds balance\\nUnknown location (pc=0:931)'})"
```

Ideally Devnet would do the same as alpha-goerli.

**Comment by internnos** [comment]
from the devnet outputs, the error seems to raise from `Error message: ERC20: transfer amount exceeds balance`

even alpha-goerli outputs

```
Actual fee exceeded max fee.
4952850074293 > 1
```
are we still using this output?

thank you

@FabijanC @ivpavici

**Comment by FabijanC** [comment]
> are we still using this output?

I don't understand your question. The issue description states the difference between the alpha-goerli and the Devnet response. You should reproduce this yourself by sending a transaction with insufficient fee. In the end, we would like Devnet to behave same way as alpha-goerli for this particular case.

**Comment by internnos** [comment]
> > are we still using this output?
> 
> I don't understand your question. The issue description states the difference between the alpha-goerli and the Devnet response. You should reproduce this yourself by sending a transaction with insufficient fee. In the end, we would like Devnet to behave same way as alpha-goerli for this particular case.

sorry for not being clear. what i meant is that, the devnet error you gave contains `ERC20: transfer amount exceeds balance` which is not about fee, but rather about `trying to send more token than the user has` so I just think the alpha-goerli output is actually wrong. but maybe i got the wrong idea!

will inspect this tonight and see what can i do tomorrow!

thank you

**Comment by FabijanC** [comment]
The output of alpha-goerli is almost never wrong and I would say definitely not wrong in this case. It is not clear from Devnet's response what subtraction overflow means in this case. I know about a user who was confused by that error message because they weren't aware that there is some fee subtracted from an account's balance. But if Devnet had reported the same error message that alpha-goerli reports, it would have been clearer what was the cause of the user's problem.

**Comment by ivpavici** [comment]
@internnos hi! Is this feature still something you are interested in contributing?

**Comment by internnos** [comment]
> @internnos hi! Is this feature still something you are interested in contributing?

hi ivan, sorry i totally forget about this  :"(((

i'm on! will start doing it this afternoon! is that okay for you?

**Comment by ivpavici** [comment]
no worries @internnos , there's no rush, just wanted to make sure!

**Comment by internnos** [comment]
@ivpavici thank you ivan! on it!

**Comment by internnos** [comment]
i'm still trying to reproduce this issue, it would be very helpful if there's example payload!

@ivpavici

**Comment by ivpavici** [comment]
@internnos from my understanding this can be achieved when sending _any_ transaction that needs to send a fee, but that fee not being high enough... so the error (in the description) said that actual fee sent (1) is less than the current network necessary fee (4952850074293 )

**Comment by internnos** [comment]
@ivpavici sorry i haven't been able to reproduce this error. i tried setting the fee to 0 but its still working.

feel free if anyone want to take this issue!

**Comment by tonypony220** [comment]
up

**Comment by FabijanC** [comment]
I've changed the duration tag to `Duration: few days` so now you can go deeper.
