### ISSUE TITLE
Support high number of concurrent connections

### ISSUE THREAD

**Issue by JorikSchellekens** [0xSpaceShard/starknet-devnet#290]
**Describe the bug (observed vs expected behavior)**

In our test suite we have a number of tests which produce a large number of concurrent calls, their order is not important so it's fine for the devnet to fulfil them in a linear order. However after about 100 open connections the devnet drops new connections with `ECONNRESET`. Here is the error from starknet.js:

```
     Uncaught RuntimeError: abort(Error: Could not POST from endpoint `http://127.0.0.1:5050/feeder_gateway/call_contract?blockNumber=pending`: request to http://127.0.0.1:5050/feeder_gateway/call_contract?blockNumber=pending failed, reason: connect ECONNRESET 127.0.0.1:5050). Build with -s ASSERTIONS=1 for more info.
```

After some digging it turns out Guicorn couldn't handle this number of open connections. I tried many different configurations of Guinicorn. Mostly these configurations related to the following ridiculous combination:

```
        self.cfg.set("worker_connections", 1000000)
        self.cfg.set("backlog", 1000000)
        self.cfg.set("keepalive", 1000000)
```

I got this working by replacing Gunicorn with waitress and setting the `connection_limit` to a high number (1000) along with increasing my ulimit locally.

I know this is a rare use case but would be good to have some cli args to support this case. I'm not sure if there is a way to get Gunicorn working or if switching to watiress or some other WSGI server is worth it.

**Not reproducible on alpha-goerli**

- [x] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**To Reproduce**

I don't have a small example but just run 200 calls concurrently on the devnet.

**Devnet version**

- I am using Devnet version: 0.3.0
- [ ] This happens with a dockerized Devnet (check the box if true).

**System specifications**

- OS: Macos 12.2.1
- Python version: 3.9.13

**Comment by FabijanC** [comment]
@Solpatium wdyt?

**Comment by Solpatium** [comment]
It seems that the default (sync) worker indeed has a problem with that. I switched to `gthread` with a big timeout and it works:
```
        self.cfg.set("worker_class", "gthread")
        self.cfg.set("timeout",  100)
```

and it works now with 200 requests. @JorikSchellekens can you check if this helps?

Apart from that I think ideal solution would be to process requests in a non-linear way, but this requires a large refactor 🤔 

<details>
<summary>Code used for testing</summary>

```python
import asyncio
import os

from starknet_py.contract import Contract
from starknet_py.net import AccountClient
from starknet_py.net.gateway_client import GatewayClient

# Local network
from starknet_py.net.models import StarknetChainId

from starkware.starknet.testing.starknet import Starknet

# The path to the contract source code.
CAIRO_PATH = os.path.join(
    os.path.dirname(__file__), "cairo-contracts/src"
)
CONTRACT_FILE = os.path.join(
    CAIRO_PATH, "openzeppelin/token/erc20/presets/ERC20Mintable.cairo"
)

CALLS_COUNT = 200


async def test():
    client = GatewayClient("http://localhost:5050")
    account = await AccountClient.create_account(client, chain=StarknetChainId.TESTNET)
    account = AccountClient(address=account.address, client=client, signer=account.signer,
                            chain=StarknetChainId.TESTNET)

    tx = await Contract.deploy(
        account,
        compilation_source=[CONTRACT_FILE],
        constructor_args=[1, 2, 3, 4, 5, 6],
        search_paths=[CAIRO_PATH],
    )
    contract = tx.deployed_contract

    promises = []
    for _ in range(CALLS_COUNT):
        promises.append(contract.functions["balanceOf"].call(account.address))

    print("LEN", len(promises))
    print(
        await asyncio.gather(*promises)
    )


asyncio.run(test())
```
</details>

**Comment by JorikSchellekens** [comment]
I used this on my use case and it wasn't working, the only thing that works for it is a switch to waitress. We should be releasing my use case of the devnet soon and then I can link to the relevant example.

**Comment by JorikSchellekens** [comment]
That said it did handle a lot more tests before it started failing so it is in the right direction.
