### ISSUE TITLE
Performance degradation

### ISSUE THREAD

**Issue by ivpavici** [0xSpaceShard/starknet-devnet#293]
**Describe the bug (observed vs expected behavior)**

After introducing the rpc v0.6.0 we observe a performance degradation. Starknet.js tests take ~x2 time to finish than before

example:
https://github.com/starknet-io/starknet.js/actions/runs/7208337084

In Starknet.js github actions we observed:
- devnet `0c82d023` was the last commit before 0.6 spec that finished in under 10 minutes on github Actions
- example: https://github.com/starknet-io/starknet.js/actions/runs/6956455935

Also, devnet tag `0.5.1` i.e. `78527decb3f76c4c808fa35f46228557af3df385` finished in 170 seconds on a local env (with a modified retryInterval of 100 ms)

**Not reproducible on alpha-goerli**

- [x] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**To Reproduce**

1. Run devnet together with the Starknet.js test suite

**Devnet version**

- I am using Devnet version:
- [ ] This happens with a dockerized Devnet (check the box if true).
- This does not appear on the following Devnet version:

**System specifications**

- OS:

**Comment by marioiordanov** [comment]
just to point that the example link - 

> example: https://github.com/starknet-io/starknet.js/actions/runs/6956455935

Uses commit https://github.com/0xSpaceShard/starknet-devnet-rs/commit/638a11adc96d443d03b04fc0d5c13c8a1e3bfc5b
