### ISSUE TITLE
Add a command to abort blocks

### ISSUE THREAD

**Issue by fracek** [0xSpaceShard/starknet-devnet#417]
At the moment, devnet supports the `/create_block` and `/create_block_on_demand` commands to add blocks to the chain. These methods are incredible for testing anything that integrates with the RPC since we can use them to construct any type of block.

It would be incredibly useful to add a `/abort_blocks_after` command to mark all blocks after the specified as aborted. Like in the StarkNet gateway/RPC, clients can access these blocks only by hash but not by number (since they don't belong to the canonical chain anymore).

This feature enables developers to test their code to handle chain reorganizations, which infrequently happen on StarkNet.

**Comment by mikiw** [comment]
@fracek Let's say we have blocks:
- 0x1 (ACCEPTED_ON_L2)
- 0x2 (ACCEPTED_ON_L2)
- 0x3 (ACCEPTED_ON_L2)

so the expectation of calling `/abort_blocks_after?blockHash=0x2` is that state of the blockchain will be updated and after calling `get_block` we will have changed state (also new block can be mined like 0x4):
- 0x1 (ACCEPTED_ON_L2)
- 0x2 (ABORTED)
- 0x3 (ABORTED)
- 0x4 (ACCEPTED_ON_L2)

is that correct?

**Comment by mikiw** [comment]
@fracek what should happen with the status of transactions whose block has been aborted? Transactions should be rejected?

**Comment by fracek** [comment]
We should double check with nodes, because the same transaction can be included in the new blocks if the previous were rejected.

**Comment by mikiw** [comment]
How can we do that? There is no other nodes concept in devnet.

Also during `/abort_blocks_after` call, we don't know if these transactions will be in next block/blocks.

**Comment by mikiw** [comment]
During the development, I encountered this code:
```
class BaseResponseObject:
    """
    Contains common functionality to response objects from the FeederGateway.
    """

    @marshmallow.post_dump
    def remove_none_values(self, data: Dict[Any, Any], many: bool = False) -> Dict[Any, Any]:
        return {key: value for key, value in data.items() if value is not None}
```

which is preventing of `block.dump()` with aborted status which is valid block...

**Comment by mikiw** [comment]
@fracek are you sure that these block should be `aborted` not `rejected`? For RPC in pathfinder node they use only `rejected` status and the have this mapping `Aborted => BlockStatus::Rejected` 

```
    impl From<starknet_gateway_types::reply::Status> for BlockStatus {
        fn from(status: starknet_gateway_types::reply::Status) -> Self {
            use starknet_gateway_types::reply::Status::*;

            match status {
                // TODO verify this mapping with Starkware
                AcceptedOnL1 => BlockStatus::AcceptedOnL1,
                AcceptedOnL2 => BlockStatus::AcceptedOnL2,
                NotReceived => BlockStatus::Rejected,
                Pending => BlockStatus::Pending,
                Received => BlockStatus::Pending,
                Rejected => BlockStatus::Rejected,
                Reverted => BlockStatus::Rejected,
                Aborted => BlockStatus::Rejected,
            }
        }
    }
```

**Comment by fracek** [comment]
Yeah I agree in the rpc it should be rejected, I called it aborted because that's how it's (was?) called in the gateway.
