### ISSUE TITLE
ServerDisconnectedError while invoking large contract

### ISSUE THREAD

**Issue by mikiw** [0xSpaceShard/starknet-devnet#420]
**Describe the bug (observed vs expected behavior)**

When we run `scratch.py` script attached to this issue which is executing a large kakarot contract devnet will fail with `http.client_exceptions.ServerDisconnectedError: Server disconnected`.

The problem will disappear when we use rust vm `-e STARKNET_DEVNET_CAIRO_VM=rust`.

- [x] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**To Reproduce scenario 1**

1. In one terminal run devnet as docker image `docker run -p 5050:5050 ghcr.io/sayajin-labs/kakarot/devnet:latest`
2. In second terminal install `starknet-py = "0.14.0a0"` and `typeguard = "2.13.0"` and run `python ./scratch.py`
[scratch.zip](https://github.com/Shard-Labs/starknet-devnet/files/10989810/scratch.zip)
3. It should fail like this:
![image](https://user-images.githubusercontent.com/5063930/225590548-05ce1f52-4e42-4757-bb25-9ca5cf162292.png)
![image](https://user-images.githubusercontent.com/5063930/225590618-24e6ddf3-2ce5-4de7-b2d0-b3581421dc1f.png)

**Devnet version**

- I am using Devnet version:
- [x] This happens with a dockerized Devnet (check the box if true).
- This does not appear on the following Devnet version:

**System specifications**

- OS:
- CPU:
- Memory:
- Python version:

**Comment by FabijanC** [comment]
What happens if you start devnet with an increased `--timeout <SECONDS>`? It defaults to 60 seconds.

**Comment by mikiw** [comment]
**To Reproduce scenario 2**
Steps to reproduce the behavior after timeout increased:

1. Run docker container
1.1 Docker
Start docker:
```
sudo /etc/init.d/docker start
docker run -p 5050:5050 -e STARKNET_DEVNET_CAIRO_VM=rust ghcr.io/sayajin-labs/kakarot/devnet:latest
```

1.2 Just run devnet with state generated in docker as devnet.pkl file:
```
poetry run starknet-devnet --seed 0 --host "0.0.0.0" --port "5050" --load-path "devnet.pkl" --disable-rpc-request-validation --timeout "300"
```

**Comment by mikiw** [comment]
There is multiple issues here

1. First and the most important one is this:

2. When devnet is lagging Metamask is trying to fetch future blocks (the same way it's fetching them in Ethereum), probably based on some past assumptions about how fast blocks are produced. It can lead to the situation that we have 20 block and metamask is trying to fetch block number 50.
3. In Metamast some transactions are marked as failed (which is correct behaviour) but some on them doesn't and metamask try to update them constantly (even when CI/CD kakarot setup changed) but I would say it's just metamask problem
![image](https://user-images.githubusercontent.com/5063930/227906141-4dc411f9-ce69-4458-a97a-375a514122fd.png)

**Comment by mikiw** [comment]
Ok, I have some updates, I think that I know what is going on here:
- The first problem is the integration problem. If you deploy contracts from remix using metamask (in my case it was 3 of them), they will be processed normally with accepted on l2 status but metamask will not detect that because of Remix<->metamask<->RPC<->starkscan integration problem and it will try to redeploy them so blockchain will grow. We can also see errors related to that like not existing transactions, and querying blocks that are not there when the blockchain was restarted without a load of the previous state. [We can't do anything about that, maybe it's an RPC issue.]
- The second problem is that once you are in this state and contracts are redeployed constantly (in my case 3 of them) after a while (~ between block 15-25) the function apply_state_updates() in starknet code base is failing because of "Invalid transaction nonce." (which makes sense in this case!). Maybe we can fix that on a devnet level code base. After that failure https://devnet.starkscan.co/ will lose track even though you can use devnet after that. Just new blocks/transactions will not show in starkscan. Also, strange thing is that after a while apply_state_updates() function needs more time to process kakarot operations. In the beginning, it takes 50 seconds, and later 60s, 70s, 80s, 90s, 100s, etc but this operation should be linear in time, here maybe someone from starknet team should take a look. [In this problem, we will take action and see how to fix it.]

**Comment by mikiw** [comment]
although I could reproduce the "Invalid transaction nonce." issue in the case of chainlink contracts there is no exponential memory leak over 1-2 hours that is happening with kakarot's contracts
