### ISSUE TITLE
Wrap BadRequest error logs when forking

### ISSUE THREAD

**Issue by FabijanC** [0xSpaceShard/starknet-devnet#423]
When defaulting to the forked network, if the requested object is missing (e.g. an undeclared class), the feeder gateway client logs the error (without actually raising) - this is not a bug, but may be misleading.

This should be handled in origin.py; we could use the same mechanism used in ForkedState (and apply it in other places in ForkedState where missing)

**Comment by tonypony220** [comment]
assign me please
