### ISSUE TITLE
Reduce the line count of starknet_wrapper

### ISSUE THREAD

**Issue by FabijanC** [0xSpaceShard/starknet-devnet#427]
The default linter setting is to treat files with >1000 lines as bad. We are very close to reaching this threshold in `starknet_wrapper.py`. Some simple manipulations can be done (like removing empty lines and editing docstring) but these aren't long-term solutions. A better solution would be to move some functionality into the utility file or, even better, to a dedicated file. All of this without achieving circular imports.

**Comment by FabijanC** [comment]
Might be solved via https://github.com/Shard-Labs/starknet-devnet/issues/152

**Comment by DaVinciDz** [comment]
Hey @FabijanC , I'm wiling to help here, please assign this issue to me.

**Comment by ivpavici** [comment]
@DaVinciDz hi! can you please reach out to us on Discord?

**Comment by DaVinciDz** [comment]
> @DaVinciDz hi! can you please reach out to us on Discord?

Hey, @ivpavici ... should i reach out throuhg the devnet channel on Discord ?

**Comment by ivpavici** [comment]
@DaVinciDz sure!
