### ISSUE TITLE
Introduce the rust impl. Poseidon hashing

### ISSUE THREAD

**Issue by ivpavici** [0xSpaceShard/starknet-devnet#434]
Probably wrap the Rust implementation of Poseidon hash from the Pathfinder project into a standalone python package for it to be included in the devnet.

Potentially with https://pyo3.rs/

Let's keep this issue as a placeholder !

**Comment by kkovaacs** [comment]
One notable thing to mention is that while the wrappers implemented in Pathfinder certainly help with Poseidon hashing performance some things are still rather inefficient. Notably, class hash calculation is implemented in Cairo, with the Poseidon hash implementation using only the `poseidon_perm` primitive. This is still significantly slower than a full-Rust class hash implementation (on the order of >10s for a fairly trivial class).
