### ISSUE TITLE
Update JSON-RPC schema to v0.3.0

### ISSUE THREAD

**Issue by FabijanC** [0xSpaceShard/starknet-devnet#443]
https://github.com/starkware-libs/starknet-specs/blob/v0.3.0-rc1/api/starknet_api_openrpc.json

Should resolve #401 (and close #412 ?)

**Comment by cptartur** [comment]
We'll work on this on Software Mansion side.

**Comment by bartekryba** [comment]
Hey, fyi I'm working on this, you can see the progress here: https://github.com/bartekryba/starknet-devnet/pull/2

I'm hoping on opening pr for review later this week.

**Comment by FabijanC** [comment]
Any update?

**Comment by cptartur** [comment]
> Any update?

We're in progres of internally reviewing the linked PR with RPC update.

**Comment by bartekryba** [comment]
I just opened a PR https://github.com/0xSpaceShard/starknet-devnet/pull/467
