### ISSUE TITLE
X is not allowed in the libfuncs 

### ISSUE THREAD

**Issue by gaetbout** [0xSpaceShard/starknet-devnet#454]
At the moment the devnet it 1 to 1 with tesnet1 however it has some limitation.
For example when trying to make use of check_ecdsa_signature(a, b, c) compiling and declaring this the contract I'm running into 
`Compilation failed. Error: Libfunc ec_point_from_x_nz is not allowed in the libfuncs list 'Default libfunc list'`
I know this limitation was lifted from testnet2.

Would it be possible to to do the same for the devnet?

**Comment by FabijanC** [comment]
Are you using a custom compiler?

**Comment by gaetbout** [comment]
Yes, I'm trying with compiler alpha.7

**Comment by FabijanC** [comment]
Can you provide a minimal contract which causes this failure? Are you able to compile it locally? I assume you need to provide some flag(s) to the compiler; do you know which ones?

**Comment by gaetbout** [comment]
Managed to declare the small contract I sent but with the full contract we are developping it I'm still running into: 
`Error: Libfunc ec_point_from_x_nz is not allowed in the libfuncs list`

**Comment by gaetbout** [comment]
Just tried with this:
```rust
#[account_contract]
mod ArgentAccount {
    use ecdsa::check_ecdsa_signature;

    struct Storage {
        lama: felt252, 
    }

    #[external]
    fn test(hash: felt252, signature: Array<felt252>) -> bool {
        check_ecdsa_signature(hash, lama::read(), *signature[0], *signature[1])
    }
}

```

**Comment by gaetbout** [comment]
Ok when declaring, the order of args matter... So my mistake!

**Comment by gaetbout** [comment]
Doing first:
`starknet-compile ../contracts/ account.json --allowed-libfuncs-list-name experimental_v0.1.0`
Then 
`starknet declare --feeder_gateway_url http://127.0.0.1:5050/feeder_gateway --gateway_url http://127.0.0.1:5050/gateway --compiler_dir ../cairo/target/release --wallet=starkware.starknet.wallets.open_zeppelin.OpenZeppelinAccount  --network alpha-goerli --contract account.json`

**Comment by FabijanC** [comment]
I am not able to compile this lama account contract. Which compiler should I be using? Are there any other dependencies?

**Comment by gaetbout** [comment]
Still using alpha.7

**Comment by FabijanC** [comment]
I am able to compile and declare the lama account contract. I used `v1.0.0-alpha.7` when compiling and configured Devnet to use the same compiler.

**Comment by gaetbout** [comment]
If anyone runs into this, you need to declare using --network alpha-goerli2
