### ISSUE TITLE
Enabling HTTPS (SSL certs)

### ISSUE THREAD

**Issue by starknetdev** [0xSpaceShard/starknet-devnet#455]
**I would like to run devnet from a public server and require the server to be accessed over HTTPS.**

There currently isn't a way to provide devnet with my SSL certificates, something I believe is required in order for HTTPS to be set up. I suggest that starknet-devnet and the docker image (the way I'm currently running devnet on the server) take an argument `--ssl_certs` that allows me to pass both public and private keys to the server app.

Open to suggestions but believe this is the best way to implement, and can't see a simple alternative other than providing the certificates to the app, though I'm no expert so please check if I've missed something.

Here's what gpt suggested based on your code in `server.py`:

```
def main():
    """Runs the server."""

    args = parse_args(sys.argv[1:])

    # ... (the rest of the code remains the same)

    print(f" * Listening on https://{args.host}:{args.port}/ (Press CTRL+C to quit)")
    try:
        GunicornServer(app, args).run(
            keyfile='key.pem',
            certfile='cert.pem'
        ) # ADD CERTS
    except KeyboardInterrupt:
        pass
    finally:
        # ... (the rest of the code remains the same)


def load_config(self):
    self.cfg.set("bind", f"{self.args.host}:{self.args.port}")
    self.cfg.set("workers", 1)
    self.cfg.set("timeout", self.args.timeout)
    self.cfg.set("keyfile", self.options['keyfile']) # ADD
    self.cfg.set("certfile", self.options['certfile']) # ADD
    # ... (the rest of the code remains the same)
```

- [x] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**To Reproduce**

docker-compose.yaml

```
  devnet:
    image: shardlabs/starknet-devnet:latest
    command:
    - "--host=0.0.0.0"
    - "--port=5050"
    - "--disable-rpc-request-validation"
    ports:
    - 5050:5050
```

shell
```
curl -X POST https://survivor-indexer.bibliothecadao.xyz:5050/rpc -d '{"jsonrpc":"2.0","method":"starknet_getTransactionByHash","params":["0x04a92239a974ec20d46bcb7ba9526d5b77c09c5679b4202a73102ddf7da6cd44"],"id":1}' -H "Content-Type: application/json"
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to survivor-indexer.bibliothecadao.xyz:5050 
```

**Devnet version**

- I am using Devnet version: v0.5.1
- [x] This happens with a dockerized Devnet (check the box if true).

**System specifications**

- OS: Amazon Linux 2 (run on container `shardlabs/starknet-devnet:latest`)
- CPU: t2.medium (EC2)
- Memory: 4GB RAM, 30GB storage
- Python version: 3.9

**Comment by ivpavici** [comment]
Hello!
Braavos achieved this, but I don't know how (https://devnet.braavos.app):
https://braavos.notion.site/FAST-dApp-Development-with-Braavos-and-Cloud-Devnet-df9d5949273c483ab9e1d721d1329e33#207aa51033d441faa6de825dc7f806e0

...so it should be possible without changing the devnet

**Comment by ivpavici** [comment]
https://github.com/BibliothecaDAO/realms-contracts/issues/321#issuecomment-1537189460
