### ISSUE TITLE
Adapt to JSON RPC API spec v0.3.0

### ISSUE THREAD

**Issue by FabijanC** [0xSpaceShard/starknet-devnet#476]
Currently adapted to v0.3.0-rc1

**Comment by bartekryba** [comment]
Hey, I'll take care of that

**Comment by mikiw** [comment]
Hi @bartekryba so in `rpc_spec.py` we have `# All usages of "oneOf" have been replaced by "anyOf"`. What was the motivation behind that? Devnet was not working properly with "oneOf"?
