### ISSUE TITLE
starknet-devnet 0.5.2 fails to execute starknet-sierra-compile when using poetry

### ISSUE THREAD

**Issue by cfal** [0xSpaceShard/starknet-devnet#478]
**Describe the bug (observed vs expected behavior)**

starknet-devnet 0.5.2, poetry 1.4.2, on linux

when using the poetry workflow, starknet-sierra-compile is missing the execute bit and cannot be executed:

```
[Errno 13] Permission denied: '/home/user/.cache/pypoetry/virtualenvs/starknet-devnet-brjde5mH-py3.9/lib/python3.9/site-packages/starkware/starknet/compiler/v1/bin/starknet-sierra-compile'
```

note that the error message is hidden right now due to https://github.com/0xSpaceShard/starknet-devnet/pull/479

reproduce from git root by:

1. `poetry env remove python` - remove any old virtualenv
2. `poetry shell`
3. `poetry update`
4. `poetry run starknet-devnet --port 5050`
5. declare/deploy any contract so that starknet-sierra-compile is called

**Comment by FabijanC** [comment]
Additional input from @cfal, the default compiler binary might not be executable, so it needs to receive the `+x` permission. We don't know exactly why it's happening.
