### ISSUE TITLE
JSON-RPC API trace methods are missing

### ISSUE THREAD

**Issue by FabijanC** [0xSpaceShard/starknet-devnet#481]
The three methods should be added: https://github.com/starkware-libs/starknet-specs/blob/v0.3.0-rc1/api/starknet_trace_api_openrpc.json

The link is for v0.3.0-rc1, but whichever is the current version at the time of development should be added (e.g. v0.3.0)

Note from Ariel:
> ...some of the methods there are still not implemented by existing nodes. For example, Pathfinder recently added simulate , but for nodes who don’t re-execute txs and rely on proofs, traceTransaction is problematic because it may require the replay of the entire block (this is currently unsupported there).

**Comment by ivpavici** [comment]
For starknet.js, `starknet_simulateTransaction` is the most important one

**Comment by mikiw** [comment]
yes v0.3.0 is there https://github.com/starkware-libs/starknet-specs/blob/v0.3.0/api/starknet_trace_api_openrpc.json

**Comment by mikiw** [comment]
PR with `starknet_simulateTransaction` is here https://github.com/0xSpaceShard/starknet-devnet/pull/492

`starknet_traceTransaction` and `simulated_transactions` will be added soon

**Comment by mikiw** [comment]
https://github.com/0xSpaceShard/starknet-devnet/pull/492 PR with `starknet_simulateTransaction` was merged
