### ISSUE TITLE
Mainnet & Devnet differences, sequencer method `get_full_contract` & `get_class_by_hash` should return abi property of type string

### ISSUE THREAD

**Issue by notV4l** [0xSpaceShard/starknet-devnet#497]
On Mainnet Sequencer, for a Sierra / cairo1 contract,  `get_full_contract` & `get_class_by_hash` method returns an object with a property `abi` of type string

ex : https://alpha-mainnet.starknet.io/feeder_gateway/get_full_contract?contractAddress=0x060cf64cf9edfc1b16ec903cee31a2c21680ee02fc778225dacee578c303806a&blockNumber=latest

https://alpha-mainnet.starknet.io/feeder_gateway/get_class_by_hash?classHash=0x021b9a01b8f17682f92c18ac4fa08ea90b371f07e27cd08de8451892546d341f&blockNumber=latest

Devnet Sequencer (for a Sierra / cairo1 contract) returns an abi in json
It should be a string (same way than RPC)

**Comment by FabijanC** [comment]
I am not able to reproduce this. I just declared and deployed a cairo1 contract, and both `get_full_contract` and `get_class_by_hash` are returning a stringified ABI.

Can you revalidate your report?

**Comment by notV4l** [comment]
Sorry, my bad i was testing with starknet.js which modifies responses types.
