### ISSUE TITLE
Forked devnet incompatible with Cairo 1 contracts deployed on origin

### ISSUE THREAD

**Issue by PhilippeR26** [0xSpaceShard/starknet-devnet#508]
**Describe the bug (observed vs expected behavior)**

Hello,
I have forked testnet (with starknet-devnet 0.5.3) :
`starknet-devnet --seed 0 --fork-network alpha-goerli`
Then I try to interact with  contracts previously created in Testnet .
If it's a Cairo 0 smart-contract, it's OK. (ex : 0x05f7cd1fd465baff2ba9d2d1501ad0a2eb5337d9a885be319366b5205a414fdd)
If it's a Cairo 1 smart-contract, it fails (ex : 0x697d3bc2e38d57752c28be0432771f4312d070174ae54eef67dd29e4afb174)
`Starknet.js error : GatewayError: Class with hash 0x1dd2c8b1422132b9fed720b5a0199529fea053f0d4405774a7df256aaa981e is not declared.`
The classHash of this contract is 0x0797250693291fd38c41052d9085eee844266f22bf7e4d94523e3462737dbe62 in Testnet.
It seems that the calculation of classHash has a problem.

**Not reproducible on alpha-goerli**

- [x] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**To Reproduce**
Launch this script :
 https://github.com/PhilippeR26/starknet.js-workshop-typescript/blob/e7fb2bf80ac8c887bf31a8c61538acdf1e4aa331/src/scripts/devnet-forked/1.interact-forked.ts#L51

**Devnet version**

- I am using Devnet version: 0.5.3
- [ ] This happens with a dockerized Devnet (check the box if true).
- This does not appear on the following Devnet version:

**System specifications**

- OS:
- CPU:
- Memory:
- Python version:

**Comment by PhilippeR26** [comment]
@mikiw

**Comment by FabijanC** [comment]
I thought this was fixed in #490, but apparently it's not. I thought your issue was about the wrong response of `/feeder_gateway/get_compiled_class_by_class_hash`, which this PR actually fixed. The first task of resolving this issue would be to find out exactly what request sent by starknet.js is failing.

**Comment by hroussille** [comment]
I have a similar issue : 

The failing query is on `/feeder_gateway/call_contract?blockNumber=pending` which works fine on testnet but returns the following on devnet : 

```
{"code":"StarknetErrorCode.UNDECLARED_CLASS","message":"Class with hash 0x5cba5ebad16af1d6e6ac141fc6ac9630270efbc6d1ad49fc17754dcaedf55a4 is not declared."}
```

I investigated a bit, and it seems like `0x5cba5ebad16af1d6e6ac141fc6ac9630270efbc6d1ad49fc17754dcaedf55a4` is what the local state considers the as the compiled class hash for the following class hash `0xc921f5a858961f39e9090c4e9ee279d5b30a6ba216de3c1434e32087a824f9`

the internal state is queried and the fallback to the forked state works fine, but the call to the provider through [_get_class_by_hash](https://github.com/0xSpaceShard/starknet-devnet/blob/315ec8c7a3a2b9f90743f4625cbfd0f82cf5a9a1/starknet_devnet/forked_state.py#L95) seems to be done using the aforementioned **compiled class hash**, and not the initial class hash, is this normal ? 

I hardcoded my initial class hash and got the following error: 

```
'Unsupported compiled class format. Cairo 1.0 compiled class must contain the attribute `pythonic_hints`
```

I'm not that knowledgeable on starknet at all, not sure if that can help. Let me know if you need more information, I'll keep investigating when I find time.

**Comment by mikiw** [comment]
I'm investigating it.

**Comment by mikiw** [comment]
Seems like `call` method in the devnet starknet wrapper is operating on the local state. I'll need to discuss that with @FabijanC.

**Comment by mikiw** [comment]
Seems that our code is querying https://alpha4.starknet.io/feeder_gateway/get_class_by_hash?classHash=0x1dd2c8b1422132b9fed720b5a0199529fea053f0d4405774a7df256aaa981e&blockNumber=823891

but I'm not sure why this `classHash` is not on `alpha-goerli`

**Comment by mikiw** [comment]
I made a hardcoded if to change `0x1dd2c8b1422132b9fed720b5a0199529fea053f0d4405774a7df256aaa981e` to `0x797250693291fd38c41052d9085eee844266f22bf7e4d94523e3462737dbe62` to execute this:
https://alpha4.starknet.io/feeder_gateway/get_class_by_hash?classHash=0x797250693291fd38c41052d9085eee844266f22bf7e4d94523e3462737dbe62&blockNumber=823891

but didn't help either... still this code is failing:
```
            call_info = await state.copy().execute_entry_point_raw(
                contract_address=address,
                selector=transaction.entry_point_selector,
                calldata=transaction.calldata,
                caller_address=0,
            )
```

**Comment by PhilippeR26** [comment]
GetClassByHash provides the Sierra.

**Comment by PhilippeR26** [comment]
May be the abi provided by the sequencer isn't 100% identical to the one provided by the cairo 1 compiler that created this contract.
You should use the recovered Sierra to recalculate the classHash.
If the result is different to 0x0797250693291fd38c41052d9085eee844266f22bf7e4d94523e3462737dbe62, there is a major problem . Could be :
- Your class hash calculation. Low probability.
- The sequencer has a big bug and isn't able to generate correctly the Sierra json (in accordance with cairo 1 compiler 0.6.0 or 1.1.0)

**Comment by FabijanC** [comment]
Since people still keep on reporting this issue in other communication channels, here's an

## Update
I've spoken to the maintainers of the cairo-lang package, the main dependency of starknet-devnet. The problem lies there, and we can't do much about it. That dependency is basically no longer updated since everything is switching to Rust, including Devnet, so we don't plan to fix this issue here, but hope to have a functional forking feature in the new project: [starknet-devnet-rs](https://github.com/0xSpaceShard/starknet-devnet-rs).

I'd keep this issue open for better visibility; i.e. anyone who visits this repository and opens [Issues](https://github.com/0xSpaceShard/starknet-devnet/issues) should see it right away. If the issue was closed, they'd have to search.
