### ISSUE TITLE
Unable to fork alpha-goerli on devnet

### ISSUE THREAD

**Issue by rajeebkm** [0xSpaceShard/starknet-devnet#519]
**Describe the bug (observed vs expected behavior)**

A clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem. However, prefer providing plain text.

**Not reproducible on alpha-goerli**

- [X] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**To Reproduce**

1. eval "$(pyenv init -)"
2. starknet-devnet -fork-network alpha-goerli --timeout 5000

**Devnet version**

- I am using Devnet version: 0.5.5
- [ ] This happens with a dockerized Devnet (check the box if true).
- This does not appear on the following Devnet version:

**System specifications**

- OS: Mac
- CPU: Apple M1
- Memory: 8 GB
- Python version: 3.9.14

<img width="1421" alt="Screenshot 2023-08-10 at 13 45 14" src="https://github.com/0xSpaceShard/starknet-devnet/assets/97892873/9a569a92-a845-4dc3-ac1c-c95d1698b515">

**Comment by FabijanC** [comment]
Hi, thanks for reporting. Can you try using the pre-released starknet-devnet version 0.6.0a0 published last week?
https://github.com/0xSpaceShard/starknet-devnet/releases/tag/v0.6.0a0

A new stable release is coming very soon (0.6.0), but for now the pre-release should do.

**Comment by rajeebkm** [comment]
Yes. it's working with starknet-devnet version [0.6.0a0].
Thanks

**Comment by rajeebkm** [comment]
<img width="929" alt="Screenshot 2023-08-22 at 18 59 26" src="https://github.com/0xSpaceShard/starknet-devnet/assets/97892873/5e7a1092-a183-467e-97ef-2c04f0655666">

Unable to fork alpha-goerli again.

Please have a look into it.

**Comment by mikiw** [comment]
Is it possible to fork mainnet?

On Discord, I can see that testnets are still 0.12.1 but maybe they updated something without notification?

**Comment by mikiw** [comment]
Testnet is 0.12.2 currently and devnet is still not adopted to that.

**Comment by rajeebkm** [comment]
> Is it possible to fork mainnet?
> 
> On Discord, I can see that testnets are still 0.12.1 but maybe they updated something without notification?

Yes, mainnet, we can fork.

**Comment by mikiw** [comment]
I can confirm that it's all about 0.12.2 adaptations. On branch https://github.com/0xSpaceShard/starknet-devnet/tree/adaptation-to-0.12.2 forking from alpha-goerli works. Of course, there are still other problems, half of the tests are currently failing on that branch.

**Comment by rajeebkm** [comment]
- Any solutions ?

**Comment by mikiw** [comment]
- You can just wait for starknet-devnet 0.12.2 adaptations to be released (probably next week)
- You can try to use this branch while waiting https://github.com/0xSpaceShard/starknet-devnet/tree/adaptation-to-0.12.2 (current adaptations branch)

**Comment by mikiw** [comment]
@rajeebkm new version has been released, have you tried to fork testnet?

**Comment by rajeebkm** [comment]
> @rajeebkm new version has been released, have you tried to fork testnet?

Still am facing the same issue, I am able to fork mainnet, but not able to fork alpha-goerli.
Do I need to upgrade anything or install any packages ??

**Comment by mikiw** [comment]
@rajeebkm you need to update devnet to this version https://github.com/0xSpaceShard/starknet-devnet/releases/tag/v0.6.1
