### ISSUE TITLE
Performance enhancements while running tests

### ISSUE THREAD

**Issue by naps62** [0xSpaceShard/starknet-devnet#52]
I'm trying to setup a hardhat cairo project (using the starknet plugin).
I initially used this devnet to run the test suite on. But I'm noticing it is extremely slow to run tests on, comparatively to the standard `pytest` tests that one can write in Nile

I'm trying to understand what the reason is for this difference in performance, and if it's something I could maybe help fixing?

**Comment by FabijanC** [comment]
Hi, thanks for bringing this up. Other users have complained about this [on Discord](https://discord.com/channels/793094838509764618/949270323965087785).

Devnet slows down after receiving multiple complex contracts, and we've only recently started receiving complaints about this, so we have yet to investigate this in depth.

To help, you can start by answering the following questions:
- Which version of Devnet are you using?
- Which contract are you deploying/interacting with - how complex is it?
- What are your computer's specifications? Is it strong?
- Do you see this problem appearing with some contracts and with others not?

**Comment by ccarnino** [comment]
I confirm that it is quite slow for me too. It has alway been for me.

- Which version of Devnet are you using? 0.1.18
- Which contract are you deploying/interacting with - how complex is it? ERC721 with Metadata.
- What are your computer's specifications? Is it strong? Top specs MacBook Pro M1 Max, so yeah really strong.
- Do you see this problem appearing with some contracts and with others not? Deploying this ERC721 contract takes on average 30 seconds. Running tests becomes incredibly painful.

**Comment by FabijanC** [comment]
@ccarnino Thanks for responding, I've updated the list with a Docker question, can you also include that in your list.

**Comment by naps62** [comment]
Hi! answering your questions:

> Which version of Devnet are you using?

currently running devnet via docker, `shardlabs/starknet-devnet:0.1.17`. Didn't actually notice `0.1.18` was out there yet, although I imagine it's not solved there yet

> Are you running Devnet in a Docker container?

Yes. On Linux (I understand docker on Mac has some limitations).
I want to try running without it, but having some issues setting it up. However, I use docker extensively for other projects, and never had much performance problems due to it.

> Which contract are you deploying/interacting with - how complex is it?

Currently deploying very simple contracts. I'm building a starknet tutorial based in hardhat. Started with just a Counter contract, and now moving to a Rock-Paper-Scissors game. overall, extremelly simple contracts so far. This particular test file takes ~30s to run against a fresh devnet instance:

```typescript
import { starknet } from "hardhat";
import { expect } from "chai";
import { StarknetContract } from "hardhat/types";

describe("Counter", function () {
  this.timeout(30_000);

  let contract: StarknetContract;

  beforeEach(async () => {
    const counterFactory = await starknet.getContractFactory("Counter");
    contract = await counterFactory.deploy({ initial: 10, max: 100 });
  });

  it("start with the initial value", async () => {
    const { value } = await contract.call("read");
    expect(value).to.equal(10n);
  });

  it("can increment by the given argument", async () => {
    await contract.invoke("increment", { inc: 5 });

    const { value } = await contract.call("read");
    expect(value).to.equal(15n);
  });

  it("cannot increment by an amount larger than the cap", async () => {
    try {
      await contract.invoke("increment", { inc: 101 });
      expect(false);
    } catch (err: any) {
      expect(err.toString()).to.include("is out of range");
    }
  });
});
```

> What are your computer's specifications? Is it strong?

Currently on a Linux desktop with AMD Ryzen 5 3600X, 16GB RAM, and M.2 storage. cpu/ram usage remain pretty normal when running these tests

> Do you see this problem appearing with some contracts and with others not?

Seems to be general. I can't think of a simpler example to test than this `Counter.cairo`

**Comment by ccarnino** [comment]
I am running devnet installed on the machine. No docker

**Comment by ccarnino** [comment]
And for reference to deploy the OpenZeppelin account contract, my machine takes about 10 seconds.

**Comment by FabijanC** [comment]
@ccarnino Thanks for the feedback, this conversation was continued on Discord: https://discord.com/channels/793094838509764618/894580545311359026/951418682800746496

**Comment by FabijanC** [comment]
This issue has been addressed with `starknet-devnet` v0.1.20: https://github.com/Shard-Labs/starknet-devnet/releases/tag/v0.1.20
Changes include a new server container and the ability to use `--lite-mode` which skips some hash calculations that the average user can live without.

**Comment by jrocco2** [comment]
I can confirm that even with `--lite-mode` the tests are still very slow.

**Comment by ivpavici** [comment]
Repoen this one as a placeholder for future improvements
